# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: DimitarRadenkov.Pointframe.Cli
PackageVersion: 6.7.21
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: Pointframe.Cli.exe
  PortableCommandAlias: pointframe
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/dimitar-radenkov/Pointframe/releases/download/v6.7.21/Pointframe.Cli-6.7.21-win-x64.zip
  InstallerSha256: 0589CF934189B1332D41C8B12EA3DA1C7124CBC82B927DF9FADEB6F4468A6BBF
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-03
